### ISSUE TITLE
Give hints when password not strong enough

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/rcp-strong-passwords#1]
Customer requested the following feature:

> I've seen you have a useful addon which only says "Please use a strong password" when the password typed is not compliant. 
> 
> Would you be able to add a hint for the user how a strong password looks like (what's expected from him to introduce - like 2 capital letters, minimum 8 chars etc)

**Comment by mindctrl** [comment]
Related: customer would like to see a password strength meter. I think that's a good idea to improve the flow.

**Comment by pippinsplugins** [comment]
I agree.

**Comment by nosegraze** [comment]
I've gotten several requests for clarifying what criteria are required for a "strong password".

**Comment by nosegraze** [comment]
PR: #8

![rcp-password-weak](https://user-images.githubusercontent.com/6324272/37515374-813b1c62-2902-11e8-98d8-919525c541ce.png)

![rcp-password-medium](https://user-images.githubusercontent.com/6324272/37515379-84802a98-2902-11e8-8044-ec6263fb63c3.png)

![rcp-password-strong](https://user-images.githubusercontent.com/6324272/37515381-849ddb4c-2902-11e8-8ac9-60ff01cc06bb.png)
