### ISSUE TITLE
Consider showing password requirements before form is submitted

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/rcp-strong-passwords#11]
I've seen this requested a couple times. People are confused about what the requirements are.

The plugin shows a strength indicator, but nowhere does it show the rules until after the form is submitted - at which point it adds this error: `Your password must be at least 8 characters long and include letters, numbers, and symbols.`.

I think we should include that message somewhere, maybe in the strength indicator that shows on the keyup event.

**Comment by nosegraze** [comment]
PR: #14

![rcp-password](https://user-images.githubusercontent.com/6324272/41532541-5dd9a716-72ef-11e8-85e7-aa93c210ed9d.png)

**Comment by mindctrl** [comment]
@nosegraze I think we probably need to enforce a `display: block` on this. Thoughts?

![image](https://user-images.githubusercontent.com/1254870/41539220-37c1a024-72db-11e8-9ac1-32a56857ea0e.png)

**Comment by nosegraze** [comment]
Yes, good idea. The theme I was using has `display: block` on the input elements, which is why mine looked better, haha. But not all themes do that.

**Comment by nosegraze** [comment]
Updated!
