### ISSUE TITLE
Enforce strong passwords on password reset and edit profile

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/rcp-strong-passwords#2]
A customer pointed out:

> If i want to manually import a csv database with users, and then have them use the reset function to obtain access, then there is really no enforcing of password strength at any time.

**Comment by nosegraze** [comment]
PR: #3

Haven't tested the password reset one but edit profile seemed okay.

**Comment by mindctrl** [comment]
Tested reset and it works fine.
