### ISSUE TITLE
Add strength meter to "forgot password" reset page and "edit password" page

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/rcp-strong-passwords#9]
Got a request from a customer.

**Comment by nosegraze** [comment]
PR: #10

**Comment by mindctrl** [comment]
As far as I see, the [password_form] shortcode in RCP never loads the scripts, because it checks for an option that doesn't exist:

`if( isset( $rcp_options['front_end_validate'] ) ) {`

https://github.com/restrictcontentpro/restrict-content-pro/blob/2.9.11/includes/shortcodes.php#L411

**Comment by erfanmhd** [comment]
i need strength meter js to load inside new pass page too. 
the plugin is only working on edit profile and registration now! 

any hint ?

**Comment by nosegraze** [comment]
@erfanmhd Can you please submit a support ticket here to discuss further: https://restrictcontentpro.com/support/
